### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MrMrRobat** [omarryhan/aiogoogle#11]
On my macOS I getting this error while using ClientSession with default ssl context. It's known issue of aiohttp

```py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x10c1a56a0>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
```
### See reasons here:
https://github.com/aio-libs/aiohttp/issues/2822
### Solved here (library level): 
https://github.com/dephell/dephell/issues/185 

### Also for quick solution on user level (without changing library itself) see (macOS only):
https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org

**Comment by omarryhan** [comment]
Like you said, this an Aiohttp related issue, not Aiogoogle. I'll close this issue now. Let me know if there's something I'm missing and I'll reopen it. Thanks

**Comment by MrMrRobat** [comment]
> if there's something I'm missing and I'll reopen it.

But as I said, it we can fix it on a library level via `certifi`. It's widely used in other libraries to deal with aiohttp ssh certificate issues. Would we?

**Comment by omarryhan** [comment]
What are the downsides of using `certifi` by default? It wasn't mentioned here: "https://github.com/aio-libs/aiohttp/issues/2822"

Generally, I think it's better we stick with the recommendations of the Aiohttp team unless we have a good reason not to. E.g. the lib is no longer being maintained.
