### ISSUE TITLE
URL formatting breaks the people.connections.list method

### ISSUE THREAD

**Issue by adam-expa** [omarryhan/aiogoogle#113]
From the docs this is how the url is supposed to be formatted:
https://developers.google.com/people/api/rest/v1/people.connections/list
```
https://people.googleapis.com/v1/{resourceName=people/*}/connections
```

However when I run this code:

```python
 async with Aiogoogle(user_creds=user_creds) as aiogoogle:
    people_v1 = await aiogoogle.discover('people', 'v1')
    full_res = await aiogoogle.as_user(
      people.connections.list(
          personFields='names,phoneNumbers',
          resourceName="people/me",
      )
      full_res=True
    )
```

I get the error:
```bash
https://people.googleapis.com/v1/people%2Fme/connections?personFields=names%2CphoneNumbers
```

The issue is that you are not excluding `/` here https://github.com/omarryhan/aiogoogle/blob/master/aiogoogle/resource.py#L32 and `people/me` is being formatted into `people%2Fme`

This is a blocking issue as it means this API endpoint cannot be reached with the lib.

**Comment by omarryhan** [comment]
Hey, thanks for filing the issue and sorry for the inconvenience!

This issue relates to #104, #96 & #63

I just released a new version that should fix the issue you're facing. 

new version is 5.0.0.
