### ISSUE TITLE
paginn issue

### ISSUE THREAD

**Issue by dev-point-team** [omarryhan/aiogoogle#121]
`next_page_generator` fail after first page because `user_creds` not passed in `sess.send`
https://github.com/omarryhan/aiogoogle/blob/aed668e06efb62600fd0b291dee4a9ff66fdb49e/aiogoogle/models.py#L361

fixed by edit to :
`prev_res = await sess.send(next_req, full_res=True, auth_manager=prev_res.auth_manager,user_creds=user_creds)`

**Comment by omarryhan** [comment]
Hi, thank you for filing the issue. Can you give a more detailed reproduction please? Also, which version you're on?

**Comment by dev-point-team** [comment]
seems rar condition, i use customed oauth wish not flow the standards
