### ISSUE TITLE
FYI sending messages with Gmail doesn't work

### ISSUE THREAD

**Issue by bryanhpchiang** [omarryhan/aiogoogle#131]
Bad Request

Content:
{'code': 400,
 'errors': [{'domain': 'global',
             'message': "'raw' RFC822 payload message string or uploading "
                        'message via /upload/* URL required',
             'reason': 'invalidArgument'}],
 'message': "'raw' RFC822 payload message string or uploading message via "
            '/upload/* URL required',
 'status': 'INVALID_ARGUMENT'}

Seems like aiogoogle is putting the body as query params into the URL rather than posting it as a body.

Given the exact same `raw_string` (base64 encoded email body), the following code works (although it's not async).
```
service = build('gmail', 'v1', credentials=creds)
# await aiog.as_user(gmail.users.messages.send(userId='me', body={"raw": raw_string}))
message = (service.users().messages().send(userId='me', body={'raw': raw_string})).execute()
```

**Comment by omarryhan** [comment]
Sorry about that! @asparagusbeef 
I would greatly appreciate if you can point me to where exactly in the docs you'd like to see this documented
