### ISSUE TITLE
Should attributes in `HTTPError` be type annotated?

### ISSUE THREAD

**Issue by wenleix** [omarryhan/aiogoogle#139]
e.g. `HTTPError.res` seems always be with type `aiogoogle.models.Response | None` (created in https://github.com/omarryhan/aiogoogle/blob/def000abd51e716239a84ba6367ea8cbe606f878/aiogoogle/models.py#L479-L480)

I can help prepare an PR if it sound reasonable? Thanks!

**Comment by omarryhan** [comment]
Yes, very reasonable, thank you so much!
