### ISSUE TITLE
support for earthengine api

### ISSUE THREAD

**Issue by dfguerrerom** [omarryhan/aiogoogle#147]
I just discovered this repository and it looks really nice for the purpose that I want to use in my current workflow.
Looking at the code,  I found that the default google discovery url is: `"https://{api}.googleapis.com/$discovery/rest?version={api_version}"`, however, the [Google Earth Engine API](https://developers.google.com/earth-engine/reference/rest) is under a different url, i.e: `https://earthengine.googleapis.com/$discovery/rest?version={version}`, is there a native way to change this url so I can get the discovery document?

**Comment by omarryhan** [comment]
Hi @dfguerrerom 

I think [this](https://github.com/omarryhan/aiogoogle/issues/144) comment should resolve your issue. I think maybe we can add this note in the 404 error (if it works for you)?

**Comment by dfguerrerom** [comment]
it worked!! thanks, yes... I think we could add a hint if users are trying to access to v2

**Comment by omarryhan** [comment]
Glad I could help! I don’t think it’s easy to figure out which apis should use which format. Have to look at Google’s lib code for that. But in the meanwhile, I think it’d be nice to add the possible fix in the error that is thrown? I would happily accept a PR with that. Thanks!
