### ISSUE TITLE
bad request content

### ISSUE THREAD

**Issue by GDjkhp** [omarryhan/aiogoogle#152]
my code returns a bad link (400)

`https://www.googleapis.com/drive/v3/files/permissions?body=%7B%22type%27%3A+%27anyone%27%2C+%27role%27%3A+%27reader%27%70`

```
{'code': 400,
 'errors': [{'domain': 'global',
             'location': 'permission.type',
             'locationType': 'other',
             'message': 'The permission type field is required.',
             'reason': 'required'}],
 'message': 'The permission type field is required.'}
```

```python
await aiogoogle.as_user(
    drive_v3.permissions.create(
        fileId=file_or_folder_id,
        body={'type': 'anyone', 'role': 'reader'}
    )
)
```

**Comment by omarryhan** [comment]
Hi, please use ‘json’ instead for passing the request json body

**Comment by GDjkhp** [comment]
![image](https://github.com/user-attachments/assets/14537d1d-3ce2-40ea-8060-ac47e81bf641)

like this? it still doesn't work

**Comment by omarryhan** [comment]
No, json={“type”: …
