### ISSUE TITLE
Is it possible to use your library in same manner?

### ISSUE THREAD

**Issue by kiddick** [omarryhan/aiogoogle#3]
https://github.com/eshmu/gphotos-upload/blob/master/client_id.json
Here is example of client auth parameters. 
So I am reading this config to CLIENT_CREDS dict and creating instance like this:
```python
async with Aiogoogle(client_creds=CLIENT_CREDS) as aiogoogle:
    photos = await aiogoogle.discover('photoslibrary', 'v1')
```
In doc examples you are using `as_user` everywhere.. 
```python
        json_res = await aiogoogle.as_user(
            drive_v3.files.list(),
        )
```
What should I use in this case.. since I have some kind of client auth. I need to use API in that manner https://github.com/eshmu/gphotos-upload/blob/master/upload.py#L156

**Comment by omarryhan** [comment]
Hey, I don't think you can upload to Google Photos using an API key or only your client creds. You need to get an access and refresh token through OAuth2. 

Here's an example: https://aiogoogle.readthedocs.io/en/latest/#oauth2-example.

If you already have an access and refresh token. Then, pass them on to Aiogoogle's UserCreds model. e.g.:

`
from aiogoogle.auth.creds import UserCreds

credentials = ...  # Assuming you already have this
user_creds = UserCreds(access_token=credentials.access_token, refresh_token=credentials.refresh_token, expires_in=credentials.expires_in)
async with Aiogoogle(client_creds=CLIENT_CREDS, user_creds=user_creds):
	....
`

Here are some more references I think you might find useful:

https://developers.google.com/photos/library/guides/authentication-authorization
https://developers.google.com/photos/library/guides/create-albums
https://developers.google.com/photos/library/reference/rest/v1/albums/create

**Comment by kiddick** [comment]
Thanks for links and example. Digging into that. Actually since I've figured out how to get access_token I am able to use `as_user` properly as an other examples! :smile:

**Comment by omarryhan** [comment]
Awesome! Happy to help :)
