### ISSUE TITLE
Support Compute Engine default service account

### ISSUE THREAD

**Issue by fredo838** [omarryhan/aiogoogle#37]
This repo is looking awesome! I know the documentation mentions that
Compute Engine default credentials are not yet supported. I was just 
wondering if this will be supported any time soon? I would help, but `async` is 
simply above me. I'll remove the issue as soon as you give an indication (not in 
the foreseeable future / I don't know is also an indication). Thanks!

**Comment by omarryhan** [comment]
Hey Fredo, thanks :)

I just added the basic service account feature about a week ago and the reason why I didn't implement GCE default service account authentication as well is that I'm not sure if there's a reliable way to test it other than spinning up a GCE container everytime I make a change, which is too much hassle for a service I don't currently use 😅.

Someone posted a [workaround](https://github.com/omarryhan/aiogoogle/issues/9#issuecomment-702166362) a while ago, maybe you can use that for now until someone implements this feature?

It should be a fairly simple feature to add though. If you're willing to give it a try, I can give you guidance along the way.

> I'll remove the issue as soon as you give an indication (not in
the foreseeable future / I don't know is also an indication).

Nah it's fine, let's keep it open. This seems to be an important feature request.

**Comment by omarryhan** [comment]
Hey @fredo838 

So I had some free time on my hand and just added the feature. I haven't pushed to master yet. You can find the new version in the gce_service_account [branch](https://github.com/omarryhan/aiogoogle/tree/gce_service_account).

If you have the time, can you test things out in a GCE environment? If all checks out, I'll go ahead and merge it to master and make a new release.

I also updated the docs in case you're not sure how to use the GCE feature. Thanks.

**Comment by fredo838** [comment]
I got the following Error message : `    await aiogoogle.service_account_manager.detect_default_creds_source()
  File "/usr/local/lib/python3.8/site-packages/aiogoogle/auth/managers.py", line 1254, in detect_default_creds_source
    await self.refresh()
  File "/usr/local/lib/python3.8/site-packages/aiogoogle/auth/managers.py", line 1317, in refresh
    await self._set_creds_from_gce()
  File "/usr/local/lib/python3.8/site-packages/aiogoogle/auth/managers.py", line 1196, in _set_creds_from_gce
    json_res = await sess.send(req)
  File "/usr/local/lib/python3.8/site-packages/aiogoogle/sessions/aiohttp_session.py", line 173, in send
    results = await schedule_tasks()
  File "/usr/local/lib/python3.8/site-packages/aiogoogle/sessions/aiohttp_session.py", line 165, in schedule_tasks
    return await asyncio.gather(*tasks, return_exceptions=False)
  File "/usr/local/lib/python3.8/site-packages/aiogoogle/sessions/aiohttp_session.py", line 151, in get_content
    response = await get_response(request)
  File "/usr/local/lib/python3.8/site-packages/aiogoogle/sessions/aiohttp_session.py", line 147, in get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiogoogle/models.py", line 402, in raise_for_status
    raise HTTPError(msg=self.reason, req=self.req, res=self)
aiogoogle.excs.HTTPError: "  
 timestamp: "2020-12-28T17:30:25.303231Z" `, so it doesn't work yet I think (The error message is empty, it's a single `"`).  It's probably better if you could test it yourself. Instead of spinning up a `VM`, I suggest ussing `gcloud run deploy` (Docker based) or even `gcloud functions deploy` (pure python). It's Google serverless mechanic, and they both use the Compute Engine service account for authentication (by default). That way you can easily test, as the Run Instance/Function is pay-per-use.

**Comment by fredo838** [comment]
I could help you out setup a testing env if you're struggling. Do you have access to a Google Cloud Project?

**Comment by fredo838** [comment]
Side note: Looks like the workaround would work for me.

**Comment by omarryhan** [comment]
Whoops, it seems that I made a typo in the URL. It should be `default` instead of `defaults`. This should probably fix the issue you're getting.

I made a PR as well https://github.com/omarryhan/aiogoogle/pull/38.

> Do you have access to a Google Cloud Project?

No, but I can create one. If you want to create one and add me to it, that's fine too. My e m a i l is omarryhan (at) gmail.com (So that bots don't get hold of it ^^).

**Comment by fredo838** [comment]
I tested it, it's working now :D. The PR looks good to me. I don't think it makes much sense to use one of my GCP projects for the testing (when this is working). I suggest you can just merge this, and if you want to set up automatic testing you can set up your own GCP project (that way you can delete it if you don't need it anymore yourself). I tested this on Cloud Run, so you could add to the documentation that it's also working for Cloud Run/Cloud Functions. Thanks for the super quick response!

**Comment by fredo838** [comment]
#RepoStarred

**Comment by omarryhan** [comment]
No problem, happy to have helped :)

**Comment by omarryhan** [comment]
Just released v1.1.0
