### ISSUE TITLE
Using this to access Sheets API

### ISSUE THREAD

**Issue by Gugu7264** [omarryhan/aiogoogle#43]
Hey there! I found your module and it seems to be exactly what I need. But I can't find how to use it with Sheets API..
Could you explain me how to use it? I also looked at docs and couldn't understand

**Comment by omarryhan** [comment]
Hi there Gugu,

I'm glad you found this library fitting your needs. Can you be more specific about what you're struggling with so I can help you better?

Are you familiar with the sync version of this library? Or with interacting with Google APIs in general?

Are you familiar with async/await?

**Comment by Gugu7264** [comment]
Hi @omarryhan! I looked at docs but I couldn't find how to use your module to access the Google sheets api. I'm trying to fetch data from a sheet, I already created and app and I have the creds set.

I didn't know there were a sync version of this library, maybe it's more documented and I could find that here? 

And yeah I'm familiar with async/await 😊

**Comment by Gugu7264** [comment]
Also I'm currently using aiogspread to access sheets, but it's not really async, some functions like `range` are defined as async in docs but aren't...

**Comment by omarryhan** [comment]
You don't really need to know the sync version of this library. I just wanted to know if you've ever interacted with a Google API before.

This library (as well as the sync version) are general wrapper around many of Google's API, not just one.

Each Google API has a JSON spec document called the discovery document. Aiogoogle *discovers* the discovery document of the API you need and helps you in building, authorizing, then sending the request.

So for Google Sheets, you'd start by writing:

```python
async with Aiogoogle() as google:
    sheets_v4 = await google.discover('sheets', 'v4')
```

`sheets_v4` being the Google Sheets API request factory.

Then I suggest that you read these sections in the docs:
- https://aiogoogle.readthedocs.io/en/latest/#discovery-service
- https://aiogoogle.readthedocs.io/en/latest/#discovery-docs-and-the-aiogoogle-object-explained

They'll guide you through actually creating the request. Then sending it.

If there's anything unclear about the docs, please let me know so I can make them better.

Cheers

**Comment by omarryhan** [comment]
I couldn't find Aiogspread on Github. Can you post a link?

Also, there's https://github.com/burnash/gspread but it's sync only.

It offers a better abstraction over the Google Sheets API. If you're up for the challenge, you can build an async clone of it using Aiogoogle.

**Comment by Gugu7264** [comment]
Ah alright thanks a lot for this little example.

Also it's not aiogspread but gspread_asyncio, you can find it here: https://github.com/dgilman/gspread_asyncio
Sorry!

**Comment by omarryhan** [comment]
No problem, happy to help :)
