### ISSUE TITLE
Google Sign-in tokens are issued under ISS="accounts.google.com"

### ISSUE THREAD

**Issue by rocha** [omarryhan/aiogoogle#54]
It would be nice to use aiogoogle's OpenID connect manager to validate and decode JWT `id_tokens` issued by Google Sign-in. According to the documentation linked below, tokens can be issued under one of two ISSs: `htttps://accounts.google.com` or `accounts.google.com`. Currently `aiogoogle` only checks for the former.

https://developers.google.com/identity/sign-in/web/backend-auth
https://developers.google.com/identity/protocols/oauth2/openid-connect

**Comment by omarryhan** [comment]
If I understood you correctly, you want:

1. An API to manually decode and validate JWT tokens

2. Make that interface accept both `accounts.google.com` and `https://accounts.google.com` as an iss

As to #1 there already is a method called `decode_and_validate` under thr `OpenIdConnectManager` class

#2, Nice catch. I'll be happy to accept a PR.
