### ISSUE TITLE
Getting an access token

### ISSUE THREAD

**Issue by Aspect1103** [omarryhan/aiogoogle#61]
So I've been looking through the documentation for over an hour now and I still have no idea how you get an access token from an OAuth client. Can someone explain how to do it?

**Comment by omarryhan** [comment]
Sorry you had to go through that.

Do you have a client key and a client secret?

**Comment by Aspect1103** [comment]
I have a client_id and a client_secret

**Comment by omarryhan** [comment]
Are you familiar with OAuth2?

Did you try using [this](https://github.com/omarryhan/aiogoogle/blob/master/examples/auth(production_unsafe)/oauth2.py) script?

**Comment by Aspect1103** [comment]
Yea, but I just don't get how it works

**Comment by omarryhan** [comment]
Sure, that's what a refresh token is for.

Here's what you have to do.

1. Clone the repo
2. `cd` to `aiogoogle/examples`
3. `cp _keys.yaml keys.yaml`
4. add your client_id, client_secret and scopes to the yaml file
5. `cd` to `aiogoogle/examples/auth\(production_unsafe\)
6. run `python oauth2.py`
7. A webbrowser tab should open to get your conscent.
8. If everything is successful, the browser should show you your access token and refresh token.
9. Now whenever you want to use this lib, you should:

```python
async with Aiogoogle(user_creds={"access_token": '...', 'refresh_token': '...'}) as aiogoogle:
    # your code
```

**Comment by Aspect1103** [comment]
I've been trying to integrate it into my own script. Heres where I am at so far:

```
import webbrowser
from aiogoogle import Aiogoogle
from sanic import Sanic
# Custom
import Config


# Get access token
clientCreds = {
    "client_id": Config.clientID,
    "client_secret": Config.clientSecret,
    "scopes": "https://www.googleapis.com/auth/drive.metadata.readonly",
    "redirect_uri": "http://localhost:5000/callback/aiogoogle",
}
aiogoogle = Aiogoogle(client_creds=clientCreds)
app = Sanic("Shiwkey")


@app.route("/authorize")
def authorize(request):
    if aiogoogle.oauth2.is_ready(clientCreds):
        print("ready")


webbrowser.open("http://localhost:5000/authorize")
app.run(host="localhost", port="5000")
```

But it just keeps giving me an internal server error

**Comment by omarryhan** [comment]
Is there a specific reason why you want to integrate it in your script? If you'll be the only one using it, then it'll be way easier for you to get the access and refresh token only once by running the script I linked to. And then using them in your script. As far as I remember, the refresh token you'll get should have no expiry.

**Comment by Aspect1103** [comment]
I thought the refresh token did expire?

**Comment by omarryhan** [comment]
No. The access token expires. You use a refresh token to get a fresh access token every time one expires.

**Comment by omarryhan** [comment]
It's possible that a refresh token might expire in 6 months or a year if it's not being used. I remember reading something like that once in the docs.

**Comment by Aspect1103** [comment]
So can I store the access token and every time I run my program, just grab that token and refresh it?

**Comment by omarryhan** [comment]
You don't have to do it manually. Just pass both the access and refresh token and aiogoogle will take it from there. It will refresh the access token right before it expires.

**Comment by Aspect1103** [comment]
Damm, that makes so much more sense. Thanks alot!

**Comment by omarryhan** [comment]
No problem, happy to help.
