### ISSUE TITLE
Bug in `authorization_url` scopes parsing?

### ISSUE THREAD

**Issue by Ahsoka** [omarryhan/aiogoogle#71]
This doesn't seem right to me.

https://github.com/omarryhan/aiogoogle/blob/8fd6b73d0ddc0035dea77e232205a452777f46da/aiogoogle/auth/managers.py#L406-L407

Should it be?
```py
scopes = scopes or client_creds["scopes"]
scopes = " ".join(scopes)
```

**Comment by omarryhan** [comment]
Yeah, you're right. Nice catch!
Crazy how this was spotted after more than 2 years.
Happy to accept a PR or change it myself if you don't have the time.

**Comment by Ahsoka** [comment]
Hmmmm.... that you for the offer but for now I think it would be best if you changed it since I don't know if I can make a PR in a timely fasion.

**Comment by omarryhan** [comment]
Sure, will push a fix now.
