### ISSUE TITLE
Bug in `authorization_url` `include_granted_scopes` parameter

### ISSUE THREAD

**Issue by Ahsoka** [omarryhan/aiogoogle#72]
When `include_granted_scopes` is not passed in as a parameter, the following error occurs:
![Screenshot (444)](https://user-images.githubusercontent.com/34612646/133947646-c46e1129-b8d9-462d-87e4-84c634110c33.png)

This is because when you do `json.dumps(include_granted_scopes)` it bypasses the if statement.
https://github.com/omarryhan/aiogoogle/blob/8fd6b73d0ddc0035dea77e232205a452777f46da/aiogoogle/auth/managers.py#L412-L423

Maybe something like this instead:
```py
for param_name, param in {
    "client_id": client_creds["client_id"],
    "response_type": response_type,
    "state": state,
    "access_type": access_type,
    "include_granted_scopes": include_granted_scopes,
    "login_hint": login_hint,
    "prompt": prompt,
}.items():
    if param is not None:
        uri += f"&{parse.urlencode({param_name: json.dumps(param) if isinstance(param, bool) else param})}"
```

**Comment by omarryhan** [comment]
Agreed 👍

**Comment by Ahsoka** [comment]
Also I just noticed that here I used an `f-string`, not sure if this library is meant to be compatible pre Python 3.6.  If so, then you will have to remove it.

**Comment by omarryhan** [comment]
Yeah, 3.6 is the oldest version we support. So we should be all good. Thanks for the heads up.

**Comment by omarryhan** [comment]
Thanks! will release a new version once CI is done
