### ISSUE TITLE
Dependency graph in GitHub for aiogoogle points to wrong repo

### ISSUE THREAD

**Issue by Ahsoka** [omarryhan/aiogoogle#73]
Not sure if this something you can do anything about, but adding `aiogoogle` to your `requirements.txt` or `setup.py` file will point to [google-cloud-aiohttp](https://github.com/Skorpyon/google-cloud-aiohttp), instead of this repo.  See this image for reference:
![Screenshot (445)](https://user-images.githubusercontent.com/34612646/133952880-baa9b4f5-4757-423f-bc99-24226b639b4f.png)

**Comment by omarryhan** [comment]
Not sure what I can do about this :/
Not sure why Github doesn't use Pypi's db and uses random setup.py(s) instead.

**Comment by Ahsoka** [comment]
Maybe emailing GitHub support might be work a try? I remember once, `pandas` in the requirements.txt pointed to [this repo](https://github.com/datasciencescoop/Pandas) instead of the [real pandas](https://github.com/pandas-dev/pandas).  But then a couple days later, the issue was resolved so not sure how that happened but maybe they reached out to GitHub or something.

**Comment by Ahsoka** [comment]
> I tried searching for an email but couldn't find one. Instead there's the Github community website. But I'm just too lazy to post there. If you feel like doing it, I hereby publicly declare that you can do it on my behalf 😄

Hey thanks for the invitation but I fear that since I am not a contributor or formally associated with this repository, my request will be denied.  I found this link which might be useful: https://support.github.com/contact/bug-report.

**Comment by Ahsoka** [comment]
Let me know if you still want me to post on your behalf if you too lazy. 😁

**Comment by omarryhan** [comment]
Done!
https://support.github.com/ticket/personal/0/1319288

Not sure if you'll be able to see it through this link though. Will update this thread once I get a reply.

**Comment by Ahsoka** [comment]
Can't see it but thanks! ♥

**Comment by omarryhan** [comment]
Just got a reply from them saying they fixed it. Can you verify please?

**Comment by Ahsoka** [comment]
> Just got a reply from them saying they fixed it. Can you verify please?

Yep it's fixed 🥰
![Screenshot (450)_LI](https://user-images.githubusercontent.com/34612646/134276036-e3a84b25-7326-4761-b668-823711563475.jpg)

**Comment by Ahsoka** [comment]
Also see: https://github.com/omarryhan/aiogoogle/network/dependents

**Comment by omarryhan** [comment]
Woah, nice! Awesome seeing people using your creation. Thanks for raising the issue!

**Comment by Ahsoka** [comment]
Thanks for creating the library! Don't know what I would done without it.
