### ISSUE TITLE
Add argument to request to ignore HTTP code 400

### ISSUE THREAD

**Issue by Gitznik** [omarryhan/aiogoogle#75]
I am trying to use the package for purchase token validation and invalid tokens return an HTTP code of 400.
androidpublisher v3, purchases.products.get

In my usecase, this is expected and nothing I would want the execution to fail on. I don't think there is a way of allowing a response of 400 right now, so I've been monkey patching the `aiogoogle.models.Response.raise_for_status` method for now. 

Would be great if you could provide this option - happy to do it myself when I find some time as well.

**Comment by omarryhan** [comment]
Hey @Gitznik 

Why not just catch the HTTP error? e.g.

```python
try:
  response = await as_user(...)
except aiogoogle.excs.HTTPError as e:
  print(e.res)
```

This is the signature of the error:

```python
class HTTPError(AiogoogleError):
    def __init__(self, msg, req=None, res=None):
        self.req = req
        self.res = res
        super().__init__(msg)
```

**Comment by omarryhan** [comment]
Perfect 👍
