### ISSUE TITLE
Pip install on windows UnicodeDecodeError

### ISSUE THREAD

**Issue by CrystalMediaDesign** [omarryhan/aiogoogle#8]
Hi,

This package generates the following error if it's being installed on Windows with pip. No errors on Linux.

```
 ERROR: Complete output from command python setup.py egg_info:
    ERROR: ['MANIFEST.in', 'pip-delete-this-directory.txt', 'PKG-INFO', 'README.md', 'requirements.txt', 'setup.cfg', 'setup.py', 'test_requirements.txt', 'tox.ini']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-_nfr2x8z\aiogoogle\setup.py", line 18, in <module>
        long_description = fh.read()
      File "C:\ProgramData\Anaconda3\envs\project\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2972: character maps to <undefined>
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-_nfr2x8z\aiogoogle\
```

If `open` statements in `setup.py` are used with `encoding="utf-8"` the package can be installed without errors.

Thanks,

**Comment by bcaudell95** [comment]
@CrystalMediaDesign I experienced the same error just now, but I noticed the package is written for python 3.7 when I'm only using 3.6.  Not sure if that is the cause of what we're seeing or if it's what you pointed out, but just sharing my observation.

**Comment by omarryhan** [comment]
Hey @CrystalMediaDesign , @bcaudell95 

I think this is being caused by Python reading `README.md` as ASCII and not Unicode. I just pushed a new version where `setup.py` is explicitly reading `README.md` as `utf-8`. Can you check if it works now? If it doesn't, I'll remove all emojis from the README file.

**Comment by CrystalMediaDesign** [comment]
That did it!
Thanks!
