### ISSUE TITLE
How to redirect queries to another server?

### ISSUE THREAD

**Issue by kovan** [omarryhan/aiogoogle#80]
Hi. I have a server running on localhost ([json-caching-proxy](https://github.com/sonyseng/json-caching-proxy)) that caches queries to the Google APIs, This way I can test my code against that server without worrying about quota usages. 

How can I point this library to that server? Or what would you recommend for testing without directly using Google servers?

**Comment by omarryhan** [comment]
Hey again, not sure I understand exactly what you need help with. Do you maybe need to change the the base URL of the API calls, so that your proxy handles the request? Is there a hard requirement for this caching proxy server? Maybe you can just cache in-memory using a decorator?

**Comment by kovan** [comment]
> Do you maybe need to change the the base URL of the API calls and point it at your proxy instead so that your proxy handles the request?

Yes, exactly that.

**Comment by omarryhan** [comment]
After you create your request object and before you send it via as_user()
or as_service_account() etc. You can change the URL string through the .url
property.

e.g.

req = youtube.videos.list()
req.url = '...'

**Comment by omarryhan** [comment]
I'll go ahead and close this issue now. Please reopen it if you have further question.
