### ISSUE TITLE
Missing names in aiogoogle.__all__

### ISSUE THREAD

**Issue by jupiterbjy** [omarryhan/aiogoogle#85]
Following imports:
https://github.com/omarryhan/aiogoogle/blob/4eef158c92ca710591322fbe5d2a89a2fae6c52a/aiogoogle/__init__.py#L15-L22

Is not listed in `__all__`
https://github.com/omarryhan/aiogoogle/blob/4eef158c92ca710591322fbe5d2a89a2fae6c52a/aiogoogle/__init__.py#L1

And therefore is triggering warning
![image](https://user-images.githubusercontent.com/26041217/150104157-5920c886-97a4-431f-b5da-ae23ea779659.png)

**Comment by omarryhan** [comment]
Shouldn't the `Aiogoogle` class be included in the `__all__` of client.py not that of `__init__.py`. I'm not sure though.

**Comment by jupiterbjy** [comment]
Yeah it would be simple fix but not sure if this is Pycharm reading wrong or not. I see no issue on pylint

**Comment by jupiterbjy** [comment]
I intentionally created demo code in hope to see it trigger warning on pylint, but sadly it doesn't - I can say pylint don't check it at all, and I can't find any official guideline on where it should read from.

https://github.com/numpy/numpy/blob/c30876f6411ef0c5365a8e4cf40cc3d4ba41196c/numpy/__init__.py#L231-L235

I do see other modules extend child libraries' `__all__`, which looks promising - but just to make sure I'll ask on StackOverFlow if there's any official reference or guideline about it.

**Comment by omarryhan** [comment]
Ahh, I see. That makes sense. Thanks for doing the research! If you wish to make a PR and follow this pattern, I'll go ahead and merge it.

**Comment by omarryhan** [comment]
Thanks a lot for the PR! I just released a new version.
