### ISSUE TITLE
License type in __version__.py does not match license type in LICENSE file

### ISSUE THREAD

**Issue by marpulli** [omarryhan/aiogoogle#88]
LICENSE says it's MIT but  __version__.py has GNU

**Comment by omarryhan** [comment]
Tomato, tomato :)

JK, I'm happy to go with either. Let me know your preference.

**Comment by omarryhan** [comment]
From a quick Google search. MIT is the more permissive license. So, I went ahead and fixed it in the `__version__`. Thanks for raising the issue!

**Comment by marpulli** [comment]
Thanks, yep MIT would have been the preference
